version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - simonovic86
  assignees:
  - simonovic86
  allow:
  - dependency-type: production
  ignore:
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
